name = "tamu-flower-form"
compatibility_date = "2024-09-08"
# compatibility_flags = [ "nodejs_compat" ]

[vars]
DISCORD_PUBLIC_KEY = ""

[env.staging.vars]
DISCORD_PUBLIC_KEY = ""

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"
